In [29]:
#import numpy
import numpy as np
#crear lista con numeros primos 
numeros_primos = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
numeros_primos
array_primos =np.array(numeros_primos)
array_primos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [4]:
#crear un array con ceros
array_ceros = np.zeros(10)
array_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#crear array con numeros sucesivos
array_numeros =np.arange(10)
array_numeros

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#array de 2 en hasta el 20
array_pares=np.arange(0,20,2)
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
#haciendo un reshape para 2 dimensiones 
array_pares.reshape(2,5)


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [13]:
#operacione aritmeticas con arrays
array_impares=array_pares+1
array_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [16]:
#multiplicar por 100 
array_impares*100


array([ 100,  300,  500,  700,  900, 1100, 1300, 1500, 1700, 1900])

In [18]:
#restado array
array_impares-array_pares

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
#dividir array
array_impares/array_pares

C:\Users\elmer\AppData\Local\Temp\ipykernel_10924\393424376.py:2: RuntimeWarning: divide by zero encountered in divide
  array_impares/array_pares


array([       inf, 1.5       , 1.25      , 1.16666667, 1.125     ,
       1.1       , 1.08333333, 1.07142857, 1.0625    , 1.05555556])

In [30]:
#metodo de asociacion a estadisticas
#suma
array_primos.sum()

np.int64(129)

In [31]:
#promedio
array_primos.mean()

np.float64(12.9)

In [32]:
#varianza
array_primos.var()

np.float64(73.28999999999999)

In [53]:
#numero de fibonacci desordenado 
array_fibonacci=np.array([55, 0, 144, 1, 21, 89, 5, 8, 13, 1, 32, 2, 3])
array_fibonacci


array([ 55,   0, 144,   1,  21,  89,   5,   8,  13,   1,  32,   2,   3])

In [35]:
#ordenar array de fibonacci de menos a mayor
array_fibonacci.sort()
array_fibonacci

array([  0,   1,   1,   2,   3,   5,   8,  13,  21,  32,  55,  89, 144])

In [42]:
#ordenar de mayor a menor
np.sort(array_fibonacci)[::-1]


array([144,  89,  55,  32,  21,  13,   8,   5,   3,   2,   1,   1,   0])

In [43]:
#selecionar elementos
A =np.arange(0,20,2).reshape(2,5)
A

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [44]:
#seleccionar el primer elemento 
A[0,0]

np.int64(0)

In [45]:
#selecionar cualquier elemento
A[1,3]

np.int64(16)

In [ ]:
#seleccionar por filas
A[1,:]


array([10, 12, 14, 16, 18])

In [50]:
#seleccionar por columna
A[:,3]

array([ 6, 16])

In [54]:
#utilizar filter
array_fibonacci

array([ 55,   0, 144,   1,  21,  89,   5,   8,  13,   1,  32,   2,   3])

In [55]:
array_fibonacci<20

array([False,  True, False,  True, False, False,  True,  True,  True,
        True, False,  True,  True])

In [57]:
#filtrar menores de 20
array_fibonacci[array_fibonacci<20]

array([ 0,  1,  5,  8, 13,  1,  2,  3])